### ISSUE TITLE
Kotlin MD Builders

### ISSUE THREAD

**Issue by IlyasYOY** [Steppschuh/Java-Markdown-Generator#16]
Hey there!

I wrote some MD Builders using your library.
I thought that I can add this to your project.

https://github.com/IlyasYOY/kotlin-markdown

Thank you for your work!

**Comment by IlyasYOY** [comment]
Hello! Should I consider preparing a PR or it's a bad idea to add Kotlin Builders in this project?

**Comment by Steppschuh** [comment]
Hey, sorry for not getting back to you. I checked out your repo when you created the issue, and was a little bit confused to be honest. Maybe that's because I don't use Kotlin myself, but I thought that you could use Java libraries just fine from Kotlin code (without requiring a wrapper like the one you created).

Anyhow, if you feel like this adds value for Kotlin users, please feel free to provide it as a library from your own repo. I would prefer not to include any Kotlin code in my library for simplicity.
